version: '3.9'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env/django.env
    depends_on:
      - db
    
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env/postgres.env
   
volumes:
  pgdata: